export const LAB_AI_CHAT_DAILY_REQUEST_LIMIT = 100
export const LAB_AI_CHAT_INPUT_MAX_CHARACTERS = 4000
export const LAB_AI_CHAT_VISIBLE_MESSAGE_LIMIT = 30
export const LAB_AI_CHAT_CONTEXT_MESSAGE_LIMIT = 14
export const LAB_AI_CHAT_COMPACTION_KEEP_MESSAGE_COUNT = 8
export const LAB_AI_CHAT_COMPACTION_TRIGGER_MESSAGE_COUNT = 12
export const LAB_AI_CHAT_COMPACTION_TRIGGER_ESTIMATED_TOKENS = 2400
export const LAB_AI_CHAT_COMPLETION_MAX_TOKENS = 1000
export const LAB_AI_CHAT_SUMMARY_MAX_TOKENS = 420
export const LAB_AI_CHAT_PROVIDER_TIMEOUT_MS = 35_000
export const LAB_AI_CHAT_STREAMING_TIMEOUT_MS = 150_000
export const LAB_AI_CHAT_SUMMARY_PROVIDER_TIMEOUT_MS = 28_000
export const LAB_AI_CHAT_MEMORY_SUMMARY_MAX_CHARACTERS = 2400
export const LAB_AI_CHAT_TIME_ZONE = "Asia/Seoul"
export const NANOGPT_MODELS_CACHE_TTL_MS = 15 * 60 * 1000

export function estimateLabAiChatTokens(text: string) {
  return Math.max(1, Math.ceil(text.trim().length / 4))
}
