import type { AuthUser } from "@/lib/auth/types"

export type ProfileFormState = {
  displayName: string
  nickname: string
  ageBand: string
  primaryRegion: string
  interestTags: string[]
  interestOther: string
  preferredTimeSlot: string
  weatherSensitivity: string[]
  marketingAccepted: boolean
  analyticsAccepted: boolean
  labEnabled: boolean
}

export function createProfileFormState(user: AuthUser): ProfileFormState {
  return {
    displayName: user.displayName,
    nickname: user.nickname ?? user.displayName,
    ageBand: user.ageBand,
    primaryRegion: user.primaryRegion,
    interestTags: user.interestTags,
    interestOther: user.interestOther ?? "",
    preferredTimeSlot: user.preferredTimeSlot,
    weatherSensitivity: user.weatherSensitivity,
    marketingAccepted: user.marketingAccepted,
    analyticsAccepted: user.analyticsAccepted,
    labEnabled: user.labEnabled,
  }
}

export const DASHBOARD_COPY = {
  ko: {
    badge: "my space",
    title: "내 대시보드",
    subtitle: "날씨, 프로필, 챗봇을 한눈에 관리하세요.",
    heroLead: "나의 나들이 공간",
    heroDescription:
      "실시간 날씨와 프로필 설정, 나들이 챗봇까지 하나의 화면에서 편하게 이용할 수 있습니다.",
    heroMetricsLocation: "지역 설정",
    heroMetricsInterests: "관심사",
    heroMetricsMarketing: "알림 수신",
    heroMetricsAnalytics: "분석 참여",
    redirecting: "로그인이 필요합니다. 로그인 페이지로 이동합니다.",
    loading: "대시보드를 불러오는 중...",
    weatherTitle: "지금 날씨",
    weatherDescription: "현재 위치 또는 설정된 지역의 실시간 날씨와 시간별 흐름을 확인하세요.",
    weatherRefresh: "새로고침",
    weatherLoading: "날씨 정보를 불러오고 있어요.",
    weatherError: "날씨 정보를 가져오지 못했어요. 잠시 후 다시 시도해 주세요.",
    profileTitle: "프로필 수정",
    profileActionHint: "취향 설정 관리",
    profileDescription: "가입 시 설정한 취향을 여기서 바로 수정할 수 있어요.",
    chatbotTitle: "나들이 챗봇",
    chatbotDescription: "날씨와 프로필을 바탕으로 나들이 계획을 도와드릴게요.",
    chatbotNotice: "현재 UI만 준비되어 있으며, 실제 응답은 아직 연결 전이에요.",
    chatbotPlaceholder: "오늘 전주에서 어디 가면 좋을까요?",
    chatbotSend: "보내기",
    chatbotIntro: "안녕하세요! 나들이 계획을 함께 세워볼까요?",
    chatbotPending: "답변을 준비하고 있어요.",
    chatbotSuggestedLabel: "빠른 질문",
    accountTitle: "내 계정",
    accountDescription: "이메일, 가입일, 로그아웃 등 계정 정보를 확인할 수 있어요.",
    dangerTitle: "계정 삭제",
    dangerDescription: "탈퇴하면 저장된 모든 데이터가 삭제됩니다. 계속하려면 DELETE를 입력해 주세요.",
    deletePlaceholder: "DELETE 입력",
    deleteAction: "탈퇴하기",
    logoutAction: "로그아웃",
    saveAction: "저장하기",
    saveSuccess: "프로필이 업데이트되었어요.",
    saveError: "저장에 실패했어요. 다시 시도해 주세요.",
    deleteError: "탈퇴 처리에 실패했어요.",
    deleteSuccess: "탈퇴가 완료되었어요.",
    logoutError: "로그아웃에 실패했어요. 다시 시도해 주세요.",
    location: "기준 지역",
    station: "관측 기준",
    updatedAt: "업데이트",
    source: "데이터 소스",
    email: "이메일",
    name: "이름",
    nickname: "닉네임",
    nicknameHint: "채팅에서 사용되는 이름이에요. (2~16자)",
    nicknameTag: "태그",
    joined: "가입일",
    accountStatus: "계정 상태",
    active: "정상",
    age: "연령대",
    region: "주 사용 지역",
    time: "선호 시간대",
    interests: "관심사",
    sensitivity: "민감한 날씨",
    marketing: "알림 수신 동의",
    analytics: "서비스 개선 분석 동의",
    analyticsHint:
      "동의하면 페이지 방문, 테마, 기기 정보를 일별 통계로 저장해요.",
    labFeature: "실험실 기능 활성화",
    labFeatureHint: "기본 화면과 분리된 실험 기능을 사용할 수 있어요. 언제든 끌 수 있습니다.",
    labNav: "실험실",
    yes: "동의",
    no: "미동의",
    score: "피크닉 지수",
    temp: "기온",
    feelsLike: "체감온도",
    humidity: "습도",
    wind: "풍속",
    uv: "자외선",
    pm10: "미세먼지",
    pm25: "초미세먼지",
    khai: "통합대기지수",
    bulletin: "공식 브리핑",
    breakdown: "점수 구성",
    noBulletin: "현재 표시할 공식 브리핑이 없습니다.",
    noSensitivity: "선택 없음",
    noTags: "표시할 태그 없음",
    profileHint: "취미는 최대 5개까지 선택할 수 있습니다.",
    otherInterestPlaceholder: "기타 취미를 적어 주세요",
    deleteHome: "탈퇴 후 홈으로 이동",
    weatherRetry: "다시 시도",
    dashboardNav: "대시보드",
    backHome: "홈으로 이동",
  },
  en: {
    badge: "my space",
    title: "My Dashboard",
    subtitle: "Weather, profile, and chatbot — all in one place.",
    heroLead: "My outing space",
    heroDescription:
      "View live weather, manage your preferences, and chat with the outing assistant from a single dashboard.",
    heroMetricsLocation: "Region",
    heroMetricsInterests: "Interests",
    heroMetricsMarketing: "Notifications",
    heroMetricsAnalytics: "Analytics",
    redirecting: "You need to log in first. Redirecting to login.",
    loading: "Loading dashboard...",
    weatherTitle: "Current Weather",
    weatherDescription: "Check real-time conditions and hourly forecast for your location or saved region.",
    weatherRefresh: "Refresh",
    weatherLoading: "Loading weather data.",
    weatherError: "Failed to load weather. Please try again.",
    profileTitle: "Edit Profile",
    profileActionHint: "Manage preferences",
    profileDescription: "Update the preferences you set during sign-up.",
    chatbotTitle: "Outing Chatbot",
    chatbotDescription: "Get outing suggestions based on your preferences and current weather.",
    chatbotNotice: "The chatbot UI is ready. LLM responses are being integrated.",
    chatbotPlaceholder: "Where should I go in Jeonju today?",
    chatbotSend: "Send",
    chatbotIntro: "Hello! Let's plan an outing together.",
    chatbotPending: "Preparing a response.",
    chatbotSuggestedLabel: "Quick prompts",
    accountTitle: "My Account",
    accountDescription: "View your email, join date, and manage your session.",
    dangerTitle: "Delete Account",
    dangerDescription: "Deleting your account removes all saved data permanently. Type DELETE to confirm.",
    deletePlaceholder: "Type DELETE",
    deleteAction: "Delete Account",
    logoutAction: "Log out",
    saveAction: "Save",
    saveSuccess: "Profile updated.",
    saveError: "Failed to save. Please try again.",
    deleteError: "Failed to delete account.",
    deleteSuccess: "Account deleted.",
    logoutError: "Failed to log out. Please try again.",
    location: "Region",
    station: "Station",
    updatedAt: "Updated",
    source: "Source",
    email: "Email",
    name: "Name",
    nickname: "Nickname",
    nicknameHint: "Your chat display name. (2-16 chars)",
    nicknameTag: "Tag",
    joined: "Joined",
    accountStatus: "Status",
    active: "Active",
    age: "Age range",
    region: "Region",
    time: "Preferred time",
    interests: "Interests",
    sensitivity: "Weather sensitivity",
    marketing: "Notification consent",
    analytics: "Analytics consent",
    analyticsHint:
      "When enabled, we store daily aggregates of page visits, theme, and device info.",
    labFeature: "Enable experimental lab",
    labFeatureHint: "Unlock optional experimental tools without affecting the default experience.",
    labNav: "Lab",
    yes: "Enabled",
    no: "Disabled",
    score: "Picnic score",
    temp: "Temperature",
    feelsLike: "Feels like",
    humidity: "Humidity",
    wind: "Wind",
    uv: "UV",
    pm10: "PM10",
    pm25: "PM2.5",
    khai: "KHAI",
    bulletin: "Briefing",
    breakdown: "Score breakdown",
    noBulletin: "No briefing available.",
    noSensitivity: "None selected",
    noTags: "No tags",
    profileHint: "Choose up to 5 interests.",
    otherInterestPlaceholder: "Describe your other interest",
    deleteHome: "Return home",
    weatherRetry: "Try again",
    dashboardNav: "Dashboard",
    backHome: "Go home",
  },
  zh: {
    badge: "我的空间",
    title: "我的仪表盘",
    subtitle: "天气、个人资料和聊天机器人，一目了然。",
    heroLead: "我的出行空间",
    heroDescription: "在一个界面中方便地查看实时天气、管理个人偏好，并与出行助手聊天。",
    heroMetricsLocation: "地区设置",
    heroMetricsInterests: "兴趣",
    heroMetricsMarketing: "通知接收",
    heroMetricsAnalytics: "分析参与",
    redirecting: "需要先登录。正在跳转到登录页面。",
    loading: "正在加载仪表盘...",
    weatherTitle: "实时天气",
    weatherDescription: "查看当前位置或已保存地区的实时天气和逐小时预报。",
    weatherRefresh: "刷新",
    weatherLoading: "正在加载天气信息。",
    weatherError: "无法获取天气信息。请稍后再试。",
    profileTitle: "编辑资料",
    profileActionHint: "偏好设置管理",
    profileDescription: "在这里直接修改注册时设置的偏好信息。",
    chatbotTitle: "出行聊天机器人",
    chatbotDescription: "根据您的偏好和当前天气，为您推荐出行计划。",
    chatbotNotice: "聊天界面已准备就绪，实际回复功能正在集成中。",
    chatbotPlaceholder: "今天在全州去哪里玩比较好呢？",
    chatbotSend: "发送",
    chatbotIntro: "您好！一起来制定出行计划吧。",
    chatbotPending: "正在准备回复。",
    chatbotSuggestedLabel: "快速提问",
    accountTitle: "我的账户",
    accountDescription: "查看邮箱、注册日期，并管理您的登录状态。",
    dangerTitle: "删除账户",
    dangerDescription: "删除账户将永久清除所有已保存的数据。请输入 DELETE 确认。",
    deletePlaceholder: "输入 DELETE",
    deleteAction: "注销账户",
    logoutAction: "退出登录",
    saveAction: "保存",
    saveSuccess: "个人资料已更新。",
    saveError: "保存失败，请重试。",
    deleteError: "注销处理失败。",
    deleteSuccess: "已成功注销。",
    logoutError: "退出登录失败，请重试。",
    location: "基准地区",
    station: "观测站",
    updatedAt: "更新于",
    source: "数据来源",
    email: "邮箱",
    name: "姓名",
    nickname: "昵称",
    nicknameHint: "聊天中显示的名称（2~16个字符）",
    nicknameTag: "标签",
    joined: "注册日期",
    accountStatus: "账户状态",
    active: "正常",
    age: "年龄段",
    region: "常用地区",
    time: "偏好时段",
    interests: "兴趣爱好",
    sensitivity: "敏感天气",
    marketing: "通知接收同意",
    analytics: "服务改进分析同意",
    analyticsHint: "同意后，我们会将页面访问、主题和设备信息按日统计保存。",
    labFeature: "启用实验室功能",
    labFeatureHint: "可以使用与主界面分离的实验功能，随时可以关闭。",
    labNav: "实验室",
    yes: "已同意",
    no: "未同意",
    score: "出行指数",
    temp: "气温",
    feelsLike: "体感温度",
    humidity: "湿度",
    wind: "风速",
    uv: "紫外线",
    pm10: "PM10",
    pm25: "PM2.5",
    khai: "综合空气质量指数",
    bulletin: "官方简报",
    breakdown: "评分构成",
    noBulletin: "暂无官方简报。",
    noSensitivity: "未选择",
    noTags: "暂无标签",
    profileHint: "最多可以选择 5 个兴趣标签。",
    otherInterestPlaceholder: "请填写其他兴趣爱好",
    deleteHome: "返回首页",
    weatherRetry: "重试",
    dashboardNav: "仪表盘",
    backHome: "返回首页",
  },
  ja: {
    badge: "マイスペース",
    title: "ダッシュボード",
    subtitle: "天気・プロフィール・チャットボットをひと目で管理。",
    heroLead: "お出かけスペース",
    heroDescription: "リアルタイムの天気、プロフィール設定、お出かけチャットボットまで、一つの画面で快適に利用できます。",
    heroMetricsLocation: "地域設定",
    heroMetricsInterests: "興味",
    heroMetricsMarketing: "通知受信",
    heroMetricsAnalytics: "分析参加",
    redirecting: "ログインが必要です。ログインページへ移動します。",
    loading: "ダッシュボードを読み込み中...",
    weatherTitle: "現在の天気",
    weatherDescription: "現在地または設定した地域のリアルタイム天気と時間ごとの変化を確認できます。",
    weatherRefresh: "更新",
    weatherLoading: "天気情報を読み込んでいます。",
    weatherError: "天気情報を取得できませんでした。しばらくしてからもう一度お試しください。",
    profileTitle: "プロフィール編集",
    profileActionHint: "設定の管理",
    profileDescription: "登録時に設定した嗜好をここですぐに変更できます。",
    chatbotTitle: "お出かけチャットボット",
    chatbotDescription: "天気とプロフィールに基づいて、お出かけ計画をお手伝いします。",
    chatbotNotice: "現在はUIのみ準備されています。実際の応答はまだ接続前です。",
    chatbotPlaceholder: "今日、全州でどこに行くのがおすすめですか？",
    chatbotSend: "送信",
    chatbotIntro: "こんにちは！お出かけの計画を一緒に立てましょう。",
    chatbotPending: "回答を準備しています。",
    chatbotSuggestedLabel: "クイック質問",
    accountTitle: "アカウント",
    accountDescription: "メールアドレス、登録日、ログアウトなどのアカウント情報を確認できます。",
    dangerTitle: "アカウント削除",
    dangerDescription: "退会すると保存されたすべてのデータが削除されます。続行するにはDELETEと入力してください。",
    deletePlaceholder: "DELETE と入力",
    deleteAction: "退会する",
    logoutAction: "ログアウト",
    saveAction: "保存",
    saveSuccess: "プロフィールが更新されました。",
    saveError: "保存に失敗しました。もう一度お試しください。",
    deleteError: "退会処理に失敗しました。",
    deleteSuccess: "退会が完了しました。",
    logoutError: "ログアウトに失敗しました。もう一度お試しください。",
    location: "基準地域",
    station: "観測所",
    updatedAt: "更新日時",
    source: "データソース",
    email: "メールアドレス",
    name: "名前",
    nickname: "ニックネーム",
    nicknameHint: "チャットで使用される名前です（2〜16文字）",
    nicknameTag: "タグ",
    joined: "登録日",
    accountStatus: "アカウント状態",
    active: "正常",
    age: "年齢層",
    region: "主な利用地域",
    time: "希望時間帯",
    interests: "興味・関心",
    sensitivity: "敏感な天気",
    marketing: "通知受信の同意",
    analytics: "サービス改善分析の同意",
    analyticsHint: "同意すると、ページ訪問、テーマ、デバイス情報を日別統計として保存します。",
    labFeature: "実験室機能を有効化",
    labFeatureHint: "基本画面とは別の実験機能を利用できます。いつでも無効にできます。",
    labNav: "実験室",
    yes: "同意",
    no: "不同意",
    score: "お出かけ指数",
    temp: "気温",
    feelsLike: "体感温度",
    humidity: "湿度",
    wind: "風速",
    uv: "紫外線",
    pm10: "PM10",
    pm25: "PM2.5",
    khai: "総合大気指数",
    bulletin: "公式ブリーフィング",
    breakdown: "スコア構成",
    noBulletin: "現在表示できる公式ブリーフィングはありません。",
    noSensitivity: "選択なし",
    noTags: "表示するタグがありません",
    profileHint: "趣味は最大5つまで選択できます。",
    otherInterestPlaceholder: "その他の趣味を記入してください",
    deleteHome: "ホームへ戻る",
    weatherRetry: "再試行",
    dashboardNav: "ダッシュボード",
    backHome: "ホームへ移動",
  },
} as const
