import type { AuthUser } from "@/lib/auth/types"

export type ProfileFormState = {
  displayName: string
  nickname: string
  ageBand: string
  primaryRegion: string
  interestTags: string[]
  interestOther: string
  preferredTimeSlot: string
  weatherSensitivity: string[]
  marketingAccepted: boolean
  analyticsAccepted: boolean
}

export function createProfileFormState(user: AuthUser): ProfileFormState {
  return {
    displayName: user.displayName,
    nickname: user.nickname ?? user.displayName,
    ageBand: user.ageBand,
    primaryRegion: user.primaryRegion,
    interestTags: user.interestTags,
    interestOther: user.interestOther ?? "",
    preferredTimeSlot: user.preferredTimeSlot,
    weatherSensitivity: user.weatherSensitivity,
    marketingAccepted: user.marketingAccepted,
    analyticsAccepted: user.analyticsAccepted,
  }
}

export const DASHBOARD_COPY = {
  ko: {
    badge: "my space",
    title: "내 대시보드",
    subtitle: "날씨, 프로필, 챗봇을 한눈에 관리하세요.",
    heroLead: "나의 나들이 공간",
    heroDescription:
      "실시간 날씨와 프로필 설정, 나들이 챗봇까지 하나의 화면에서 편하게 이용할 수 있습니다.",
    heroMetricsLocation: "지역 설정",
    heroMetricsInterests: "관심사",
    heroMetricsMarketing: "알림 수신",
    heroMetricsAnalytics: "분석 참여",
    redirecting: "로그인이 필요합니다. 로그인 페이지로 이동합니다.",
    loading: "대시보드를 불러오는 중...",
    weatherTitle: "지금 날씨",
    weatherDescription: "현재 위치 또는 설정된 지역의 실시간 날씨와 시간별 흐름을 확인하세요.",
    weatherRefresh: "새로고침",
    weatherLoading: "날씨 정보를 불러오고 있어요.",
    weatherError: "날씨 정보를 가져오지 못했어요. 잠시 후 다시 시도해 주세요.",
    profileTitle: "프로필 수정",
    profileActionHint: "취향 설정 관리",
    profileDescription: "가입 시 설정한 취향을 여기서 바로 수정할 수 있어요.",
    chatbotTitle: "나들이 챗봇",
    chatbotDescription: "날씨와 프로필을 바탕으로 나들이 계획을 도와드릴게요.",
    chatbotNotice: "현재 UI만 준비되어 있으며, 실제 응답은 아직 연결 전이에요.",
    chatbotPlaceholder: "오늘 전주에서 어디 가면 좋을까요?",
    chatbotSend: "보내기",
    chatbotIntro: "안녕하세요! 나들이 계획을 함께 세워볼까요?",
    chatbotPending: "답변을 준비하고 있어요.",
    chatbotSuggestedLabel: "빠른 질문",
    accountTitle: "내 계정",
    accountDescription: "이메일, 가입일, 로그아웃 등 계정 정보를 확인할 수 있어요.",
    dangerTitle: "계정 삭제",
    dangerDescription: "탈퇴하면 저장된 모든 데이터가 삭제됩니다. 계속하려면 DELETE를 입력해 주세요.",
    deletePlaceholder: "DELETE 입력",
    deleteAction: "탈퇴하기",
    logoutAction: "로그아웃",
    saveAction: "저장하기",
    saveSuccess: "프로필이 업데이트되었어요.",
    saveError: "저장에 실패했어요. 다시 시도해 주세요.",
    deleteError: "탈퇴 처리에 실패했어요.",
    deleteSuccess: "탈퇴가 완료되었어요.",
    logoutError: "로그아웃에 실패했어요. 다시 시도해 주세요.",
    location: "기준 지역",
    station: "관측 기준",
    updatedAt: "업데이트",
    source: "데이터 소스",
    email: "이메일",
    name: "이름",
    nickname: "닉네임",
    nicknameHint: "채팅에서 사용되는 이름이에요. (2~16자)",
    nicknameTag: "태그",
    joined: "가입일",
    accountStatus: "계정 상태",
    active: "정상",
    age: "연령대",
    region: "주 사용 지역",
    time: "선호 시간대",
    interests: "관심사",
    sensitivity: "민감한 날씨",
    marketing: "알림 수신 동의",
    analytics: "서비스 개선 분석 동의",
    analyticsHint:
      "동의하면 페이지 방문, 테마, 기기 정보를 일별 통계로 저장해요.",
    yes: "동의",
    no: "미동의",
    score: "피크닉 지수",
    temp: "기온",
    feelsLike: "체감온도",
    humidity: "습도",
    wind: "풍속",
    uv: "자외선",
    pm10: "미세먼지",
    pm25: "초미세먼지",
    khai: "통합대기지수",
    bulletin: "공식 브리핑",
    breakdown: "점수 구성",
    noBulletin: "현재 표시할 공식 브리핑이 없습니다.",
    noSensitivity: "선택 없음",
    noTags: "표시할 태그 없음",
    profileHint: "취미는 최대 5개까지 선택할 수 있습니다.",
    otherInterestPlaceholder: "기타 취미를 적어 주세요",
    deleteHome: "탈퇴 후 홈으로 이동",
    weatherRetry: "다시 시도",
    dashboardNav: "대시보드",
    backHome: "홈으로 이동",
  },
  en: {
    badge: "my space",
    title: "My Dashboard",
    subtitle: "Weather, profile, and chatbot — all in one place.",
    heroLead: "My outing space",
    heroDescription:
      "View live weather, manage your preferences, and chat with the outing assistant from a single dashboard.",
    heroMetricsLocation: "Region",
    heroMetricsInterests: "Interests",
    heroMetricsMarketing: "Notifications",
    heroMetricsAnalytics: "Analytics",
    redirecting: "You need to log in first. Redirecting to login.",
    loading: "Loading dashboard...",
    weatherTitle: "Current Weather",
    weatherDescription: "Check real-time conditions and hourly forecast for your location or saved region.",
    weatherRefresh: "Refresh",
    weatherLoading: "Loading weather data.",
    weatherError: "Failed to load weather. Please try again.",
    profileTitle: "Edit Profile",
    profileActionHint: "Manage preferences",
    profileDescription: "Update the preferences you set during sign-up.",
    chatbotTitle: "Outing Chatbot",
    chatbotDescription: "Get outing suggestions based on your preferences and current weather.",
    chatbotNotice: "The chatbot UI is ready. LLM responses are being integrated.",
    chatbotPlaceholder: "Where should I go in Jeonju today?",
    chatbotSend: "Send",
    chatbotIntro: "Hello! Let's plan an outing together.",
    chatbotPending: "Preparing a response.",
    chatbotSuggestedLabel: "Quick prompts",
    accountTitle: "My Account",
    accountDescription: "View your email, join date, and manage your session.",
    dangerTitle: "Delete Account",
    dangerDescription: "Deleting your account removes all saved data permanently. Type DELETE to confirm.",
    deletePlaceholder: "Type DELETE",
    deleteAction: "Delete Account",
    logoutAction: "Log out",
    saveAction: "Save",
    saveSuccess: "Profile updated.",
    saveError: "Failed to save. Please try again.",
    deleteError: "Failed to delete account.",
    deleteSuccess: "Account deleted.",
    logoutError: "Failed to log out. Please try again.",
    location: "Region",
    station: "Station",
    updatedAt: "Updated",
    source: "Source",
    email: "Email",
    name: "Name",
    nickname: "Nickname",
    nicknameHint: "Your chat display name. (2-16 chars)",
    nicknameTag: "Tag",
    joined: "Joined",
    accountStatus: "Status",
    active: "Active",
    age: "Age range",
    region: "Region",
    time: "Preferred time",
    interests: "Interests",
    sensitivity: "Weather sensitivity",
    marketing: "Notification consent",
    analytics: "Analytics consent",
    analyticsHint:
      "When enabled, we store daily aggregates of page visits, theme, and device info.",
    yes: "Enabled",
    no: "Disabled",
    score: "Picnic score",
    temp: "Temperature",
    feelsLike: "Feels like",
    humidity: "Humidity",
    wind: "Wind",
    uv: "UV",
    pm10: "PM10",
    pm25: "PM2.5",
    khai: "KHAI",
    bulletin: "Briefing",
    breakdown: "Score breakdown",
    noBulletin: "No briefing available.",
    noSensitivity: "None selected",
    noTags: "No tags",
    profileHint: "Choose up to 5 interests.",
    otherInterestPlaceholder: "Describe your other interest",
    deleteHome: "Return home",
    weatherRetry: "Try again",
    dashboardNav: "Dashboard",
    backHome: "Go home",
  },
} as const
